"""Add is_active to User model

Revision ID: 505f1fc4ddad
Revises: 647975a704b5
Create Date: 2025-05-19 03:23:56.871722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505f1fc4ddad'
down_revision = '647975a704b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
