"""Add quantity field to EquipmentRequest

Revision ID: 647975a704b5
Revises: 
Create Date: 2025-05-19 02:52:17.276805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647975a704b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_request', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
